# This is a TOML document. Boom.

title = "Configuration file for dnsproxy"
Verbose = false
LogOutput = ""
ListenAddrs = ["127.0.0.1"]
ListenPorts = [53]
#HTTPSListenPorts = ""
#TLSListenPorts = ""
#QUICListenPorts = ""
#DNSCryptListenPorts = ""
#TLSCertPath = ""
#TLSKeyPath = ""
#TLSMinVersion = ""
#TLSMaxVersion = ""
#Insecure = false
#DNSCryptConfigPath = ""
TLSAuthCertPath = "/home/marino/certificates/root/ca/intermediate/certs/dohclient.cert.pem"
TLSAuthKeyPath = "/home/marino/certificates/root/ca/intermediate/private/dohclient.key.pem"
Upstreams = ["https://dns.plido.net/dns-query"]
BootstrapDNS = ["1.1.1.1:53"]
#Fallbacks = ""
#AllServers = ""
#FastestAddress = ""
#Cache = ""
CacheSizeBytes = 64000
#CacheMinTTL = ""
#CacheMaxTTL = ""
#CacheOptimistic = ""
Ratelimit = 0
#RefuseAny = ""
#EnableEDNSSubnet = ""
#EDNSAddr = ""
#DNS64 = ""
#DNS64Prefix = ""
IPv6Disabled = false
# BogusNXDomain = ''
UDPBufferSize = 0
MaxGoRoutines = 0
Version = false
