# This is the yaml configuration file for dnsproxy with minimal working
# configuration, all the options available can be seen with ./dnsproxy --help.
# To use it within dnsproxy specify the --config-path=/<path-to-config.yaml>
# option.  Any other command-line options specified will override the values
# from the config file.
#
# TODO(m.kazantsev):  Add more default values.
bootstrap:
  - "8.8.8.8:53"
cache-size: 65536
# DNSSEC validation is enabled by default, if you want to disable it set it to
# false.
dnssec: true
hosts-file-enabled: true
https-server-name: "dnsproxy"
listen-addrs:
  - "0.0.0.0"
listen-ports:
  - 53
max-go-routines: 0
optimistic-answer-ttl: '30s'
optimistic-max-age: '12h'
pending-requests-enabled: true
ratelimit: 0
ratelimit-subnet-len-ipv4: 24
ratelimit-subnet-len-ipv6: 64
timeout: '10s'
udp-buf-size: 0
upstream:
  - "1.1.1.1:53"
upstream-mode: "load_balance"
