# Configuration file for dnsproxy

# Log settings
# // --

Verbose = true # Verbose output (optional)
LogOutput = "" # Path to a log file, if not set, write to stdout

# Listen addrs
# --

ListenAddrs = ["127.0.0.1"] # Server listen address

# Server listen ports 
ListenPorts = [53] # Listening ports. Zero value disables TCP and UDP listeners
#HTTPSListenPorts = [] # Listening ports for DNS-over-HTTPS
#TLSListenPorts = [] # Listening ports for DNS-over-TLS
#QUICListenPorts = [] # Listening ports for DNS-over-QUIC
#DNSCryptListenPorts = [] # Listening ports for DNSCrypt

# Encryption config
# --

#TLSCertPath = "" # Path to the .crt/.pem with the certificate chain, when the proxy is used as a DNS server
#TLSKeyPath = "" # Path to a file with the private key, when the proxy is used as a DNS server
#TLSMinVersion = # Minimum TLS version, for example 1.0
#TLSMaxVersion = # Maximum TLS version, for example 1.3
Insecure = false # Disable secure TLS certificate validation, for DNS server
#DNSCryptConfigPath = "" # Path to a file with DNSCrypt configuration. You can generate one using https://github.com/ameshkov/dnscrypt

#DoH Upstream Authentication
#TLSAuthCertPath = "/home/ivan/certs/root/ca/intermediate/certs/dohclient.cert.pem" # Path to a file with the client certificate, coment if you don't want to use client auth
#TLSAuthKeyPath = "/home/ivan/certs/root/ca/intermediate/private/dohclient.key.pem" # Path to a file with the client private key, coment if you don't want to use client auth

TLSAuthKeyPath = "/home/ivan/Desktop/client.key.pem"
TLSAuthCertPath = "/home/ivan/Desktop/client.cert.pem"

#Upstream DNS servers settings
#--
#Upstreams = ["https://dns.plido.net/dns-query"] # An upstream to be used (can be specified multiple times). You can also specify path to a file with the list of servers, it must be set
Upstreams = ["[/company.fr/]https://dns.plido.net/dns-query", "1.1.1.1:53"]
BootstrapDNS = ["1.1.1.1:53"] # Bootstrap DNS for DoH and DoT, can be specified multiple times 
#Fallbacks = [""] # Fallback DNS resolver to use when regular ones are unavailable, can be specified multiple times. You can also specify path to a file with the list of servers"`
#AllServers = false # If true, parallel queries to all configured upstream servers
#FastestAddress = # Respond to A or AAAA requests only with the fastest IP address, detected by ICMP response time or TCP connection time

# Cache settings
# --

#Cache = true # If true, DNS cache is enabled
#CacheSizeBytes = 64000 # Cache size value, default: 64k
#CacheMinTTL = # Minimum TTL value for DNS entries, in seconds. Capped at 3600. Artificially extending TTLs should only be done with careful consideration."`
#CacheMaxTTL = # Maximum TTL value for DNS entries, in seconds
#CacheOptimistic = # CacheOptimistic, if set to true, enables the optimistic DNS cache. That means that cached results will be served even if their cache TTL has already expired

# Anti-DNS amplification measures
# --

Ratelimit = 0 # Ratelimit (requests per second)
#RefuseAny = false # If true, refuse ANY requests

# ECS settings
# --

#EnableEDNSSubnet = true # Use EDNS Client Subnet extension
#EDNSAddr = "" # Send EDNS custom client address

#DNS64 settings
#

#DNS64 = true # If specified, dnsproxy will act as a DNS64 server
#DNS64Prefix = "" # If specified, this is the DNS64 prefix dnsproxy will be using when it works as a DNS64 server. If not specified, dnsproxy uses the 'Well-Known Prefix' 64:ff9b::

#Other settings and options
#--

IPv6Disabled = false # If true, all AAAA requests will be replied with NoError RCode and empty answer
# BogusNXDomain = [""] # Transform responses that contain at least one of the given IP addresses into NXDOMAIN. Can be specified multiple times
UDPBufferSize = 0 # Set the size of the UDP buffer in bytes. A value <= 0 will use the system default.
MaxGoRoutines = 0 # Set the maximum number of go routines. A value <= 0 will not not set a maximum default to 0
Version = false # Prints the program version"`
