---
version: 2
plan:
  project-key: AGH
  key: DNSPROXYSPECS
  name: dnsproxy - Build and run tests
variables:
  dockerGo: adguard/golang-ubuntu:5.4
  dockerLint: golangci/golangci-lint:v1.50.0

stages:
  - Lint:
      manual: false
      final: false
      jobs:
        - Lint
  - Tests:
      manual: false
      final: false
      jobs:
        - Test

Lint:
  docker:
    image: ${bamboo.dockerLint}
    volumes:
      ${system.GO_CACHE_DIR}: "${bamboo.cacheGo}"
      ${system.GO_PKG_CACHE_DIR}: "${bamboo.cacheGoPkg}"
      ${bamboo.build.working.directory}: "/app"
  key: LINT
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            golangci-lint run -v
  requirements:
    - adg-docker: 'true'

Test:
  docker:
    image: ${bamboo.dockerGo}
    volumes:
      ${system.YARN_DIR}: ${bamboo.cacheYarn}
      ${system.GO_CACHE_DIR}: ${bamboo.cacheGo}
      ${system.GO_PKG_CACHE_DIR}: ${bamboo.cacheGoPkg}
  key: TEST
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        environment: GOFLAGS="-buildvcs=false" CI="1"
        scripts:
          - |-
            set -e -f -u -x

            go version

            # Run tests.
            make VERBOSE=1 test
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 1
    after-inactive-days: 5
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
