name: Build DNSproxy

on: push

jobs:
  build_linux:
    runs-on:
      - ubuntu-latest
      - windows-latest
      - macos-latest
    steps:
      run: |
          case ${{ os.runner }} in
          ubuntu-latest | macos-latest)
          go test -mod=vendor -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...
          GOOS=windows GOARCH=386 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=windows GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=386 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=arm64 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=arm GOARM=6 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=mips GOMIPS=softfloat VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=freebsd GOARCH=arm GOARM=6 VERSION=${TRAVIS_TAG:-dev} make release
          GOOS=darwin GOARCH=amd64 VERSION=${TRAVIS_TAG:-dev} make release
          ls -l build/dnsproxy-*
          ;;
          windows-latest)
          go test -mod=vendor -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...
          ;;
          esac
