name: Build DNSproxy

on: push

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
#          - macos-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.x
      - name: Test
        run: |
          bash <(curl -s https://codecov.io/bash)
          go test -mod=vendor -race -v -bench=. -coverprofile=coverage.txt -covermode=atomic ./...

  build:
    needs:
      - tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
#      - name: Generate build number
#        uses: einaregilsson/build-number@v3
#        with:
#          token: ${{secrets.github_token}}
      - name: Build
        run: |-
          GOOS=windows GOARCH=386 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=windows GOARCH=amd64 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=386 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=amd64 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=arm64 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=arm GOARM=6 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=mips GOMIPS=softfloat VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=freebsd GOARCH=arm GOARM=6 VERSION=${GITHUB_REF##*/:-dev} make release
          GOOS=darwin GOARCH=amd64 VERSION=${GITHUB_REF##*/:-dev} make release
          ls -l build/dnsproxy-*
#  Codecover:
#    needs:
#      - Build
#    runs-on: ubuntu-latest
#    steps:
#      - name: cover
#        run: |
#          bash <(curl -s https://codecov.io/bash)
