name: Build Go Mobile for iOS (v20)

on:
  push:
    branches: [ master ]
    tags: [ 'v0.20.0' ]  # 只处理v20相关的标签
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'v0.20.0'  # 确保检出正确的tag

    - name: Create branch from tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        branch_name="release-v0.20.0"
        git show ${{ github.sha }} --quiet || git fetch --depth=1 origin ${{ github.sha }}
        git branch $branch_name ${{ github.sha }}
        git push origin $branch_name
      env:
        TAG_NAME: ${{ steps.tag.outputs.tag_name }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install Xcode dependencies
      run: |
        xcode-select --install || true
        sudo xcodebuild -license accept

    # - name: Initialize Gomobile
    #   run: |
    #     # go install golang.org/x/mobile/cmd/gomobile@a42111704963f4f0d1266674e1e97489aa8dcca0
    #     go get golang.org/x/mobile/cmd/gomobile@a42111704963f4f0d1266674e1e97489aa8dcca0
    #     go install golang.org/x/mobile/cmd/gomobile
    #     gomobile init

    - name: Run Makefile (v20)
      run: |
        ls
        cd mobile
        make ios

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-v20-output
        path: output/
