'env':
  'BASE_IMAGE': |-
    ${{ vars.BASE_IMAGE || 'adguard/go-builder:1.26.4--1' }}
  'CACHE_BUSTER': |-
    ${{ vars.CACHE_BUSTER || '0' }}
'jobs':
  'Build':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'permissions':
      # TODO(d.kolyshev): !! Back to read.
      'contents': 'write'
      # Octopass OIDC for the cross-repo token
      'id-token': 'write'
    'runs-on': 'team-go'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          # Set to false to avoid GITHUB_TOKEN leaking.
          #
          # See https://github.com/actions/checkout/issues/485#issuecomment-934422611.
          'persist-credentials': false
      - 'name': 'Build'
        'run': |
          #!/bin/sh

          set -e -f -o pipefail -u -x

          # TODO(d.kolyshev): !! Set version, revision etc.
          # TODO(d.kolyshev): !! Use AdGuardSoftwareLimited/actions.
          docker build \
              --build-arg "BASE_IMAGE=${BASE_IMAGE}" \
              --build-arg "CACHE_BUSTER=${CACHE_BUSTER}" \
              --output '.' \
              --progress 'plain' \
              --target 'builder-exporter' \
              -f ./docker/release.Dockerfile \
              .
      - 'uses': 'actions/upload-artifact@v7'
        'with':
          'name': 'dnsproxy'
          path: |
            build/dnsproxy-*
  'PublishGitHubRelease':
    'if': |
      ${{ github.repository_owner == 'AdGuardSoftwareLimited' }}
    'needs': 'Build'
    'permissions':
      # Download the artifact.
      'contents': 'read'
      # Octopass OIDC for the cross-repo token
      'id-token': 'write'
    'uses': 'AdGuardSoftwareLimited/actions/.github/workflows/create-gh-release.yml@master'
    'with':
      'artifact_name': 'dnsproxy'
      'tag_name': ''
      'team': 'go'
      # TODO(d.kolyshev): !! Add 'target_repo': 'AdGuardTeam/dnsproxy'.
      'draft': true
'name': 'Build and release on GitHub'
'on':
  'push':
    'tags':
      - 'v*'
    'branches':
      # TODO(d.kolyshev): !! Set back to master.
      - '*'
  'workflow_dispatch': null
# Permissions are disabled for all the jobs by default, and then overridden for
# specific jobs if needed.  This is a recommended practice for security reasons,
# and also allows to avoid mistakes with permissions when creating new jobs.
#
# See https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions.
'permissions': {}
