#!/bin/sh

# This comment is used to simplify checking local copies of the script.  Bump
# this number every time a significant change is made to this script.
#
# AdGuard-Project-Version: 2

set -e -f -o 'pipefail' -u

. ./scripts/hooks/helper.sh

check_unstaged_changes

lint_staged_changes
